### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by eknives** [hyongju/minUI-arcade-filename-converter#1]
Hi, It's not a bug, but is there any trick to create a collection of Neo Geo games without having the BIOS file duplicated multiple times?

Thx.

**Comment by hyongju** [comment]
Hi @eknives I can definitely do that but I’ve generated multiple copies of neogeo bios on purpose. Without adding them in each game folder neogeo game did not run for me (minUI)

**Comment by eknives** [comment]
I know the BIOS file is necessary, but I'm wondering if it's possible to use a single BIOS file and have the M3U file indicate its location.
